const masterBank = {
  "math": [

  // Algebra & Quadratic Equations
  {q: "Solve for x: x² - 9x + 20 = 0.", a: "4, 5", options: ["4, 5", "2, 10", "-4, -5", "1, 20"]},
  {q: "Find the roots of the equation: x² - x - 30 = 0.", a: "6, -5", options: ["-6, 5", "6, -5", "3, -10", "15, -2"]},
  {q: "What is the discriminant (D) of the equation 2x² + 5x + 3 = 0?", a: "1", options: ["1", "4", "25", "49"]},
  {q: "Find the value of k if x² + kx + 16 = 0 has equal roots.", a: "8 or -8", options: ["4", "8 or -8", "16", "0"]},
  {q: "If one root of x² + kx - 12 = 0 is 4, find the value of k.", a: "-1", options: ["1", "-1", "3", "-4"]},
  {q: "Solve by completing the square: x² + 8x = 9.", a: "1, -9", options: ["1, 9", "1, -9", "-1, 9", "3, -3"]},
  {q: "Find the sum of the roots of the equation 3x² - 12x + 7 = 0.", a: "4", options: ["4", "-4", "7/3", "12"]},
  {q: "Find the product of the roots of the equation 2x² + 5x - 10 = 0.", a: "-5", options: ["5", "-5", "5/2", "-10"]},
  {q: "Form a quadratic equation whose roots are 5 and -2.", a: "x² - 3x - 10 = 0", options: ["x² + 3x - 10 = 0", "x² - 3x - 10 = 0", "x² - 7x + 10 = 0", "x² + 7x + 10 = 0"]},
  {q: "The roots of x² - 6x + 9 = 0 are ______.", a: "Real and Equal", options: ["Real and Distinct", "Real and Equal", "Imaginary", "Zero"]},

  // Arithmetic & Geometry
  {q: "Express 0.00045678 correct to three significant figures.", a: "0.000457", options: ["0.000", "0.000456", "0.000457", "0.457"]},
  {q: "In a class, the ratio of boys to girls is 3:5. If there are 40 students, find the number of boys.", a: "15", options: ["15", "25", "20", "12"]},
  {q: "Convert 42 (base 10) to a number in base 2.", a: "101010", options: ["101010", "110010", "100101", "101101"]},
  {q: "A car travels 450km in 5 hours. What is its speed in m/s?", a: "25m/s", options: ["90m/s", "25m/s", "50m/s", "15m/s"]},
  {q: "If $4,000.00 earns $800.00 simple interest in 2 years, find the annual rate.", a: "10%", options: ["5%", "8%", "10%", "20%"]},

  // Trigonometry
  {q: "If sin θ = 5/13 and θ is acute, find cos θ.", a: "12/13", options: ["5/12", "12/13", "13/12", "7/13"]},
  {q: "Find the value of cos(60°) + sin(30°).", a: "1", options: ["0.5", "1", "√3", "0"]},
  {q: "In a right-angled triangle, if the hypotenuse is 10 and an angle is 30°, find the opposite side.", a: "5", options: ["5", "8.66", "10", "7.5"]},
  {q: "What is the value of tan(0°)?", a: "0", options: ["0", "1", "Undefined", "-1"]},
  {q: "The Cosine Rule for finding side 'a' is expressed as ______.", a: "a² = b² + c² - 2bc cosA", options: ["a² = b² + c²", "a/sinA = b/sinB", "a² = b² + c² - 2bc cosA", "a = b cosC"]},
  {q: "If tan θ = 3/4, find the value of sin θ + cos θ.", a: "7/5", options: ["1", "7/5", "5/7", "12/5"]},
  {q: "Find the value of x in a right-angled triangle where the hypotenuse is 12cm and the angle is 60°.", a: "6cm", options: ["6cm", "6√3cm", "12cm", "10cm"]},
  {q: "A ladder 6m long leans against a vertical wall. If it makes an angle of 30° with the wall, find the distance of the foot of the ladder from the wall.", a: "3m", options: ["3m", "3√3m", "6m", "5.2m"]},
  {q: "Evaluate: sin²(45°) + cos²(45°).", a: "1", options: ["0", "0.5", "1", "2"]},
  {q: "In triangle XYZ, x=7cm, y=5cm and Z=60°. Find the side z using the Cosine Rule.", a: "√39cm", options: ["6cm", "√39cm", "√74cm", "8cm"]},
  {q: "What is the value of sin(120°)?", a: "√3/2", options: ["1/2", "-1/2", "√3/2", "-√3/2"]},
  {q: "If the shadow of a tower 30m high is 10√3m long, find the angle of elevation of the sun.", a: "60°", options: ["30°", "45°", "60°", "90°"]},
  {q: "In a triangle, if a=10, b=12 and sin A = 0.5, find sin B using the Sine Rule.", a: "0.6", options: ["0.4", "0.5", "0.6", "0.8"]},
  {q: "Find the value of tan(135°).", a: "-1", options: ["1", "-1", "0", "Undefined"]},
  {q: "A point P is 10m away from the foot of a tree. If the angle of elevation to the top of the tree is 45°, find the height of the tree.", a: "10m", options: ["5m", "10m", "10√2m", "20m"]},
  // Sequences (AP & GP)
  {q: "Find the 15th term of the AP: 5, 9, 13, 17...", a: "61", options: ["57", "61", "65", "69"]},
  {q: "The first term of an AP is 10 and the common difference is -2. Find the 10th term.", a: "-8", options: ["-8", "-10", "8", "0"]},
  {q: "Find the 5th term of the GP: 4, 12, 36...", a: "324", options: ["108", "216", "324", "432"]},
  {q: "Find the sum to infinity of the GP: 10, 5, 2.5...", a: "20", options: ["15", "20", "25", "30"]},
  {q: "Find the geometric mean of 3 and 27.", a: "9", options: ["9", "12", "15", "81"]},

  // Statistics
  {q: "Find the mean of the numbers 12, 18, 20, 22, and 28.", a: "20", options: ["18", "20", "21", "22"]},
  {q: "Find the range of the following: 15, 89, 45, 23, 67, 12.", a: "77", options: ["89", "77", "74", "12"]},
  {q: "The median of 5, 3, 10, 5, 9, 12, 4 is ______.", a: "5", options: ["5", "7", "9", "10"]},
  {q: "Calculate the variance of the numbers 4, 6, 8.", a: "2.67", options: ["2.00", "2.67", "3.11", "4.00"]},
  {q: "Find the mean deviation of the set of numbers: 3, 5, 8, 12.", a: "3", options: ["2", "3", "3.5", "4"]},
  {q: "The weights (in kg) of five students are 40, 52, 48, 40, and 60. Find the modal weight.", a: "40kg", options: ["40kg", "48kg", "52kg", "40.5kg"]},
  {q: "If the variance of a distribution is 25, what is the standard deviation?", a: "5", options: ["2.5", "5", "12.5", "625"]},
  {q: "A bag contains 5 red balls and 3 blue balls. If a ball is picked at random, what is the probability it is blue?", a: "3/8", options: ["1/3", "3/5", "3/8", "5/8"]},
  {q: "Find the median of the following frequency distribution: 12, 15, 12, 14, 18, 15, 15, 10.", a: "14.5", options: ["14", "14.5", "15", "15.5"]},
  // Mensuration
  {q: "Find the volume of a sphere with radius 3cm in terms of π.", a: "36π cm³", options: ["12π cm³", "36π cm³", "108π cm³", "48π cm³"]},
  
  {q: "Find the area of a circle with a radius of 7cm. [Take π = 22/7]", a: "154cm²", options: ["44cm²", "154cm²", "308cm²", "616cm²"]},
  {q: "The perimeter of a square is 32cm. Find its area.", a: "64cm²", options: ["16cm²", "32cm²", "64cm²", "128cm²"]},
  {q: "Calculate the volume of a rectangular box with dimensions 5m by 4m by 3m.", a: "60m³", options: ["12m³", "20m³", "60m³", "120m³"]},
  {q: "Find the curved surface area of a cylinder with radius 7cm and height 10cm. [Take π = 22/7]", a: "440cm²", options: ["220cm²", "440cm²", "880cm²", "1540cm²"]},
  {q: "The area of a triangle is 30cm². If the base is 10cm, find the perpendicular height.", a: "6cm", options: ["3cm", "6cm", "10cm", "15cm"]},
  {q: "Find the volume of a sphere with a radius of 3cm. [Leave answer in terms of π]", a: "36π cm³", options: ["12π cm³", "18π cm³", "36π cm³", "113π cm³"]},
  {q: "A trapezium has parallel sides of 8cm and 12cm, and a height of 5cm. Find its area.", a: "50cm²", options: ["100cm²", "50cm²", "40cm²", "25cm²"]},
  {q: "Find the total surface area of a cube whose side length is 4cm.", a: "96cm²", options: ["16cm²", "64cm²", "96cm²", "128cm²"]},
  {q: "The volume of a cone is 314cm³ and its base radius is 10cm. Find its height. [Take π = 3.14]", a: "3cm", options: ["3cm", "6cm", "9cm", "12cm"]},
  {q: "Calculate the length of the diagonal of a rectangle with sides 6cm and 8cm.", a: "10cm", options: ["10cm", "12cm", "14cm", "48cm"]},
  {q: "Find the area of a sector of a circle with radius 6cm and central angle 60°. [Take π = 3.14]", a: "18.84cm²", options: ["6.28cm²", "18.84cm²", "37.68cm²", "113.04cm²"]},
  {q: "The base area of a cylinder is 154cm² and its volume is 1540cm³. Find its height.", a: "10cm", options: ["5cm", "10cm", "15cm", "20cm"]},
  {q: "Find the perimeter of a semi-circle with radius 7cm. [Take π = 22/7]", a: "36cm", options: ["22cm", "29cm", "36cm", "44cm"]},
  {q: "A rectangular tank is 2m long, 1.5m wide, and 1m deep. How many litres of water can it hold? [1m³ = 1000L]", a: "3000L", options: ["300L", "1500L", "2000L", "3000L"]},
  {q: "Find the surface area of a sphere with diameter 14cm. [Take π = 22/7]", a: "616cm²", options: ["154cm²", "308cm²", "616cm²", "2464cm²"]},
  {q: "The area of a rhombus is 24cm². If one diagonal is 6cm, find the other diagonal.", a: "8cm", options: ["4cm", "8cm", "12cm", "16cm"]},
  {q: "Find the volume of a triangular prism with a base area of 25cm² and a length of 10cm.", a: "250cm³", options: ["125cm³", "250cm³", "500cm³", "75cm³"]},
  {q: "A wire in the shape of a circle with radius 14cm is bent into a square. Find the side of the square. [Take π = 22/7]", a: "22cm", options: ["11cm", "22cm", "44cm", "88cm"]},
  {q: "Find the slant height of a cone if the radius is 3cm and the vertical height is 4cm.", a: "5cm", options: ["5cm", "7cm", "12cm", "25cm"]},
  {q: "The ratio of the radii of two spheres is 2:3. Find the ratio of their volumes.", a: "8:27", options: ["2:3", "4:9", "8:27", "16:81"]},
  {q: "The base area of a cone is 154cm² and its height is 9cm. Find its volume.", a: "462cm³", options: ["1386cm³", "462cm³", "154cm³", "231cm³"]}
],
 "english": [
  {q: "From the options lettered A to D, choose the word that best completes the sentence: The company's performance was ______ by the board.", a: "commended", options: ["commended", "recommended", "commanded", "demanded"]},
  {q: "If you don't stop playing, you ______ your exams.", a: "will fail", options: ["fail", "would fail", "will fail", "are failing"]},
  {q: "The principal warned the students against ______ in the examination hall.", a: "malpractice", options: ["malpractices", "malpractice", "misconducts", "misconduct"]},
  {q: "Choose the word nearly opposite in meaning to the underlined word: The _luxurious_ lifestyle of the king was a contrast to the ______ life of his subjects.", a: "austere", options: ["simple", "austere", "mean", "poor"]},
  {q: "The teacher was very _lenient_ with the students, but the principal was ______.", a: "strict", options: ["hard", "harsh", "strict", "wicked"]},
  {q: "While some people are _extravagant_, others are ______.", a: "frugal", options: ["miserly", "frugal", "poor", "stingy"]},
  {q: "The boy was _timid_, but his sister was ______.", a: "bold", options: ["fearless", "bold", "courageous", "audacious"]},
  {q: "Choose the word nearest in meaning to the underlined word: The _proscription_ of the union was a big blow to the workers.", a: "banning", options: ["launching", "expulsion", "banning", "removal"]},
  {q: "The _strategic_ position of the town made it a target for the enemy.", a: "tactical", options: ["ethical", "practical", "tactical", "legal"]},
  {q: "The instructions were very _explicit_.", a: "clear", options: ["vague", "clear", "brief", "detailed"]},
  {q: "He is a very _versatile_ actor.", a: "talented", options: ["talented", "famous", "popular", "skillful"]},
  {q: "The _alleviation_ of poverty is a major goal of the government.", a: "reduction", options: ["reduction", "removal", "termination", "elimination"]},
  {q: "The students were asked to ______ the passage.", a: "summarize", options: ["summarize", "analyze", "review", "restate"]},
  {q: "The committee has ______ its report.", a: "submitted", options: ["submitted", "presented", "released", "published"]},
  {q: "He was ______ of the theft.", a: "accused", options: ["accused", "charged", "blamed", "suspected"]},
  {q: "The meeting was ______ till next week.", a: "postponed", options: ["cancelled", "delayed", "postponed", "adjourned"]},
  {q: "She ______ to school every day.", a: "walks", options: ["walk", "walks", "walking", "walked"]},
  {q: "The boy ______ the book on the table.", a: "laid", options: ["lay", "laid", "lied", "lain"]},
  {q: "Neither the teacher nor the students ______ present.", a: "were", options: ["is", "was", "are", "were"]},
  {q: "The news ______ very exciting.", a: "is", options: ["is", "are", "were", "be"]},
  {q: "I have ______ my breakfast.", a: "eaten", options: ["eat", "ate", "eaten", "eating"]},
  {q: "The car belongs to ______.", a: "us", options: ["we", "us", "our", "ours"]},
  {q: "He is ______ than his brother.", a: "taller", options: ["tall", "taller", "tallest", "more tall"]},
  {q: "She is the ______ girl in the class.", a: "most beautiful", options: ["beautiful", "more beautiful", "most beautiful", "very beautiful"]},
  {q: "The man ______ stole the money has been caught.", a: "who", options: ["who", "whom", "whose", "which"]},
  {q: "This is the house ______ Jack built.", a: "that", options: ["who", "whom", "that", "which"]},
  {q: "I ______ him for a long time.", a: "have known", options: ["know", "knew", "have known", "had known"]},
  {q: "He ______ to the market yesterday.", a: "went", options: ["go", "goes", "went", "gone"]},
  {q: "The rain ______ when we arrived.", a: "had stopped", options: ["stop", "stops", "stopped", "had stopped"]},
  {q: "If I ______ a bird, I would fly.", a: "were", options: ["am", "was", "were", "be"]},
  {q: "He acts as if he ______ the boss.", a: "were", options: ["is", "was", "were", "be"]},
  {q: "I look forward to ______ you soon.", a: "seeing", options: ["see", "sees", "seeing", "seen"]},
  {q: "The table is made ______ wood.", a: "of", options: ["with", "of", "from", "by"]},
  {q: "He is good ______ Mathematics.", a: "at", options: ["in", "at", "with", "for"]},
  {q: "She is married ______ a doctor.", a: "to", options: ["with", "to", "by", "for"]},
  {q: "The cat is hiding ______ the table.", a: "under", options: ["on", "in", "under", "over"]},
  {q: "He jumped ______ the fence.", a: "over", options: ["over", "across", "through", "on"]},
  {q: "The book is ______ the bag.", a: "in", options: ["on", "in", "at", "by"]},
  {q: "He arrived ______ 10 o'clock.", a: "at", options: ["in", "at", "on", "by"]},
  {q: "She was born ______ 1995.", a: "in", options: ["in", "at", "on", "by"]},
  {q: "The evidence given by the first witness was CONCRETE, but that of the second was ______.", a: "vague", options: ["abstract", "vague", "complex", "unclear"]},
  {q: "While the first sister is known for her HUMILITY, the second is known for her ______.", a: "pride", options: ["arrogance", "pride", "insolence", "vanity"]},
  {q: "The management decided to RETAIN the senior staff and ______ the junior ones.", a: "dismiss", options: ["sack", "dismiss", "expel", "release"]},
  {q: "To prevent a crisis, the government had to RESCIND the law and ______ a new one.", a: "enact", options: ["enact", "produce", "create", "uphold"]},
  {q: "Some people are GULLIBLE, while others are ______.", a: "astute", options: ["skeptical", "shrewd", "astute", "clever"]},
  {q: "The results of the first test were PROVISIONAL, but the second were ______.", a: "final", options: ["conclusive", "final", "permanent", "fixed"]},
  {q: "The soldiers were ordered to ADVANCE, but the commander told the scouts to ______.", a: "retreat", options: ["withdraw", "retreat", "recede", "return"]},
  {q: "While the father is STINGY, the son is ______.", a: "generous", options: ["kind", "generous", "lavish", "wasteful"]},
  {q: "The climate in the north is ARID, but the south is ______.", a: "humid", options: ["wet", "moist", "humid", "damp"]},
  {q: "He is a NOVICE in the game, whereas his brother is a ______.", a: "professional", options: ["master", "professional", "expert", "veteran"]},

  // SECTION: Nearest in Meaning (Synonyms)
  {q: "The principal's speech was very IMPACTFUL.", a: "effective", options: ["touching", "effective", "impressive", "forceful"]},
  {q: "The villagers were AGHAST at the sight of the wreckage.", a: "horrified", options: ["surprised", "horrified", "amazed", "disturbed"]},
  {q: "The manager's decision was ARBITRARY.", a: "random", options: ["unfair", "random", "personal", "hasty"]},
  {q: "The lady is very METICULOUS about her appearance.", a: "careful", options: ["fussy", "careful", "proud", "conscious"]},
  {q: "The witness gave a VIVID account of the accident.", a: "clear", options: ["graphic", "clear", "detailed", "loud"]},
  {q: "The suspect's statement was INCOHERENT.", a: "unclear", options: ["meaningless", "unclear", "confusing", "false"]},
  {q: "The new policy is MANDATORY for all staff.", a: "compulsory", options: ["necessary", "important", "compulsory", "required"]},
  {q: "The heavy rain has SUBSIDED.", a: "lessened", options: ["stopped", "lessened", "ceased", "decreased"]},
  {q: "He is a very RESOURCEFUL person.", a: "inventive", options: ["talented", "inventive", "capable", "skillful"]},
  {q: "The outcome of the election was INEVITABLE.", a: "unavoidable", options: ["certain", "unavoidable", "expected", "clear"]},

  // SECTION: Sentence Completion / Grammar
  {q: "He was accused of ______ the company's funds.", a: "embezzling", options: ["stealing", "embezzling", "taking", "misusing"]},
  {q: "The judge ______ the case for lack of evidence.", a: "dismissed", options: ["cancelled", "dismissed", "closed", "stopped"]},
  {q: "The students were asked to ______ from making noise.", a: "refrain", options: ["abstain", "refrain", "stop", "cease"]},
  {q: "The boy is very good ______ drawing.", a: "at", options: ["in", "at", "with", "on"]},
  {q: "She is the ______ of the two girls.", a: "prettier", options: ["pretty", "prettier", "prettiest", "more pretty"]},
  {q: "Neither the man nor his wife ______ present at the party.", a: "was", options: ["is", "was", "are", "were"]},
  {q: "The driver was warned ______ overspeeding.", a: "against", options: ["on", "of", "against", "from"]},
  {q: "He has been living here ______ ten years.", a: "for", options: ["since", "for", "from", "during"]},
  {q: "If I ______ the money, I would have bought the car.", a: "had had", options: ["have", "had", "had had", "would have"]},
  {q: "The news ______ shared by everyone in the village.", a: "was", options: ["is", "was", "are", "were"]},
  {q: "By the time we arrived, the movie ______.", a: "had started", options: ["starts", "started", "has started", "had started"]},
  {q: "He is one of the players who ______ selected for the team.", a: "were", options: ["is", "was", "are", "were"]},
  {q: "The book is ______ interesting than the one I read last week.", a: "more", options: ["most", "very", "more", "much"]},
  {q: "She preferred dancing ______ singing.", a: "to", options: ["than", "to", "over", "from"]},
  {q: "The teacher made the students ______ the exercise.", a: "do", options: ["do", "to do", "doing", "did"]},
  {q: "The man ______ car was stolen is my uncle.", a: "whose", options: ["who", "whom", "whose", "which"]},
  {q: "I ______ my homework before my father returned.", a: "had finished", options: ["finish", "finished", "have finished", "had finished"]},
  {q: "The car was ______ damaged in the accident.", a: "badly", options: ["bad", "badly", "worse", "worst"]},
  {q: "He didn't go to school because he ______ ill.", a: "was", options: ["is", "was", "has been", "had been"]},
  {q: "The suitcase is ______ heavy for me to carry.", a: "too", options: ["so", "very", "too", "much"]}
],
  "economics": [

  // --- Economic Growth & Development ---
  {q: "Which of the same refers to the quantitative increase in a country's real output?", a: "Economic Growth", options: ["Economic Development", "Economic Growth", "Inflation", "Stagnation"]},
  {q: "The structural transformation of an economy from agrarian to industrial is known as ______.", a: "Economic Development", options: ["Economic Growth", "Economic Development", "Modernization", "Urbanization"]},
  {q: "Which of these is a major indicator of a country's standard of living?", a: "Per Capita Income", options: ["Total GDP", "Per Capita Income", "Exchange Rate", "Birth Rate"]},
  {q: "The 'vicious cycle of poverty' is mainly caused by ______.", a: "Low savings and investment", options: ["High exports", "Low savings and investment", "Foreign aid", "Technological advancement"]},
  {q: "Which index measures development using life expectancy, education, and income?", a: "HDI", options: ["GDP", "CPI", "HDI", "Gini Index"]},
  {q: "A developed economy is characterized by a large ______ sector.", a: "Tertiary", options: ["Primary", "Secondary", "Tertiary", "Agricultural"]},
  {q: "Which of the following is a barrier to economic development?", a: "Inadequate infrastructure", options: ["High literacy", "Political stability", "Inadequate infrastructure", "Low birth rate"]},
  {q: "Economic growth is best measured by the change in ______.", a: "Real GDP", options: ["Nominal GDP", "Real GDP", "Total Population", "Currency value"]},
  {q: "Underdevelopment is often associated with high ______.", a: "Dependency ratios", options: ["Capital formation", "Industrialization", "Dependency ratios", "Life expectancy"]},
  {q: "The 'take-off' stage in economic growth was popularized by ______.", a: "W.W. Rostow", options: ["Adam Smith", "W.W. Rostow", "John Keynes", "David Ricardo"]},

  // --- Balance of Trade & Payments ---
  {q: "The record of all economic transactions between a country and the rest of the world is ______.", a: "Balance of Payments", options: ["Balance of Trade", "Balance of Payments", "Capital Account", "National Budget"]},
  {q: "Visible trade refers to the export and import of ______.", a: "Tangible goods", options: ["Services", "Tangible goods", "Foreign aid", "Tourism"]},
  {q: "A surplus in the Balance of Trade occurs when ______.", a: "Exports exceed imports", options: ["Imports exceed exports", "Exports exceed imports", "Taxes are high", "Inflation is low"]},
  {q: "Which of the following is an 'invisible' item in trade?", a: "Banking services", options: ["Cocoa", "Crude oil", "Banking services", "Machinery"]},
  {q: "Devaluation of a currency is intended to ______.", a: "Make exports cheaper", options: ["Increase imports", "Make exports cheaper", "Stop inflation", "Reduce local production"]},
  {q: "The 'Terms of Trade' refers to the ratio between ______.", a: "Export and Import prices", options: ["Exports and Imports", "Export and Import prices", "Debt and GDP", "Tax and Spending"]},
  {q: "A deficit in the Balance of Payments is often settled using ______.", a: "Foreign reserves", options: ["Local currency", "Foreign reserves", "Internal loans", "Barter trade"]},
  {q: "Protectionism is a policy designed to ______.", a: "Restrict imports", options: ["Encourage imports", "Restrict imports", "Devalue currency", "Abolish tariffs"]},
  {q: "An embargo is a type of trade barrier that ______.", a: "Prohibits trade", options: ["Tax imports", "Limits quantity", "Prohibits trade", "Subsidizes exports"]},
  {q: "The Current Account includes visible trade, invisible trade, and ______.", a: "Unilateral transfers", options: ["Foreign direct investment", "Unilateral transfers", "Portfolio investment", "Gold reserves"]},

  // --- Economic Systems ---
  {q: "In which system are the means of production owned by the state?", a: "Command Economy", options: ["Market Economy", "Command Economy", "Mixed Economy", "Traditional Economy"]},
  {q: "The 'Invisible Hand' concept is associated with ______.", a: "Market Economy", options: ["Socialism", "Command Economy", "Market Economy", "Mixed Economy"]},
  {q: "A major disadvantage of a Command Economy is ______.", a: "Lack of consumer choice", options: ["High competition", "Lack of consumer choice", "Price instability", "Wasteful advertising"]},
  {q: "In a Mixed Economy, economic decisions are made by ______.", a: "Both Government and Private Sector", options: ["Government only", "Private sector only", "Both Government and Private Sector", "Tradition only"]},
  {q: "Consumer Sovereignty is a key feature of ______.", a: "Capitalism", options: ["Communism", "Capitalism", "Socialism", "Feudalism"]},
  {q: "The primary motive for production in a Capitalist system is ______.", a: "Profit", options: ["Social welfare", "Profit", "Equality", "Tradition"]},
  {q: "Which system relies on customs and beliefs to solve economic problems?", a: "Traditional Economy", options: ["Mixed Economy", "Traditional Economy", "Market Economy", "Command Economy"]},
  {q: "Price mechanism is the main tool for resource allocation in ______.", a: "Free Market Economy", options: ["Planned Economy", "Free Market Economy", "Communalism", "Mixed Economy"]},
  {q: "Public goods, like streetlights, are usually provided by the government because of ______.", a: "Market failure", options: ["High profits", "Market failure", "Low demand", "Consumer choice"]},
  {q: "Central Planning is the core characteristic of ______.", a: "Socialism", options: ["Capitalism", "Socialism", "Free Trade", "Laissez-faire"]},

  // --- Development Goals (SDGs) ---
  {q: "How many Sustainable Development Goals (SDGs) were set by the UN?", a: "17", options: ["10", "15", "17", "20"]},
  {q: "SDG 1 aims to eradicate ______.", a: "Poverty", options: ["Hunger", "Poverty", "Inequality", "Climate change"]},
  {q: "Which SDG focuses on 'Quality Education'?", a: "SDG 4", options: ["SDG 1", "SDG 2", "SDG 4", "SDG 10"]},
  {q: "The target year for achieving the SDGs is ______.", a: "2030", options: ["2020", "2025", "2030", "2050"]},
  {q: "SDG 5 is dedicated to achieving ______.", a: "Gender Equality", options: ["Clean Water", "Gender Equality", "Life on Land", "Zero Hunger"]},
  {q: "SDG 13 requires urgent action to combat ______.", a: "Climate Change", options: ["Poverty", "Illiteracy", "Climate Change", "Unemployment"]},
  {q: "The focus of SDG 2 is ______.", a: "Zero Hunger", options: ["Clean Energy", "Zero Hunger", "Peace and Justice", "Industry"]},
  {q: "Sustainable development means meeting current needs without ______.", a: "Compromising future generations", options: ["Spending money", "Using technology", "Compromising future generations", "Exporting goods"]},
  {q: "Which SDG promotes 'Decent Work and Economic Growth'?", a: "SDG 8", options: ["SDG 3", "SDG 8", "SDG 12", "SDG 17"]},
  {q: "SDG 6 ensures the availability and sustainable management of ______.", a: "Water and Sanitation", options: ["Forests", "Water and Sanitation", "Ocean life", "Electricity"]},

  // --- International Organisations ---
  {q: "The main function of the IMF is to ______.", a: "Maintain exchange stability", options: ["Provide long-term dev loans", "Maintain exchange stability", "Regulate world trade", "Eradicate malaria"]},
  {q: "Which organization is primarily responsible for global trade rules?", a: "WTO", options: ["WHO", "WTO", "UNICEF", "OPEC"]},
  {q: "The World Bank's primary focus is ______.", a: "Long-term development projects", options: ["Short-term BOP relief", "Long-term development projects", "Setting oil prices", "Military defense"]},
  {q: "OPEC is an organization of countries that ______.", a: "Export petroleum", options: ["Produce cocoa", "Export petroleum", "Fight poverty", "Maintain world peace"]},
  {q: "Which of the following is a regional economic bloc in West Africa?", a: "ECOWAS", options: ["EU", "ECOWAS", "AU", "NAFTA"]},
  {q: "The 'Lome Convention' was an agreement between the EU and ______.", a: "ACP countries", options: ["USA", "ACP countries", "China", "OPEC"]},
  {q: "The headquarters of the African Development Bank (AfDB) is in ______.", a: "Abidjan", options: ["Lagos", "Addis Ababa", "Abidjan", "Nairobi"]},
  {q: "The UN agency responsible for children's welfare is ______.", a: "UNICEF", options: ["UNESCO", "UNICEF", "UNDP", "FAO"]},
  {q: "A 'Free Trade Area' is a group of countries that ______.", a: "Remove internal trade barriers", options: ["Have a common currency", "Remove internal trade barriers", "Have a central government", "Ban all imports"]},
  {q: "Which organization replaced the GATT in 1995?", a: "WTO", options: ["IMF", "World Bank", "WTO", "UNCTAD"]},
  // --- Balance of Trade & Payments ---
  {q: "If a country exports $500M in goods and imports $350M, calculate the Balance of Trade.", a: "$150M surplus", options: ["$150M deficit", "$850M surplus", "$150M surplus", "$350M deficit"]},
  {q: "A nation has a trade deficit of $20M. If total imports are $100M, what is the value of exports?", a: "$80M", options: ["$120M", "$80M", "$20M", "$100M"]},
  {q: "Calculate the Current Account Balance: Visible Exports ($80), Visible Imports ($60), Invisible Exports ($20), Invisible Imports ($30).", a: "$10 surplus", options: ["$20 surplus", "$10 deficit", "$10 surplus", "$30 deficit"]},
  {q: "Calculate the Terms of Trade if the Index of Export Prices is 120 and the Index of Import Prices is 150.", a: "80", options: ["125", "80", "1.25", "0.8"]},
  {q: "If the exchange rate moves from $1 = ₦1,500 to $1 = ₦1,600, what is the percentage depreciation of the Naira?", a: "6.67%", options: ["10%", "6.25%", "6.67%", "15%"]},
  {q: "Total Exports are $200B and Total Imports are $215B. What is the trade position?", a: "$15B deficit", options: ["$15B surplus", "$15B deficit", "$415B total", "$5B deficit"]},
  {q: "Net Transfers = -$5M, Net Services = +$10M, Trade Balance = -$15M. Calculate the total Current Account.", a: "-$10M", options: ["-$10M", "+$10M", "-$20M", "$0"]},
  {q: "If a country imposes a 10% tariff on $50M worth of imports, calculate the government revenue.", a: "$5M", options: ["$0.5M", "$50M", "$5M", "$10M"]},
  {q: "If the Export Price Index is 110 and the Terms of Trade is 0.88, calculate the Import Price Index.", a: "125", options: ["125", "96.8", "100", "110"]},
  {q: "Total autonomous receipts are $500 and payments are $550. Calculate the BOP deficit.", a: "$50", options: ["$1,050", "$50", "$500", "$550"]},

  // --- Economic Growth & Development ---
  {q: "If real GDP was $200B in 2024 and $210B in 2025, calculate the growth rate.", a: "5%", options: ["10%", "5%", "4.7%", "2.1%"]},
  {q: "Calculate Per Capita Income if National Income is $50B and population is 25 million.", a: "$2,000", options: ["$200", "$2,000", "$5,000", "$20,000"]},
  {q: "If population grows at 3% and GDP grows at 2%, the Per Capita Income will ______.", a: "Decrease by 1%", options: ["Increase by 1%", "Stay the same", "Decrease by 1%", "Increase by 5%"]},
  {q: "GDP is $1,000. Depreciation is $100 and Indirect Taxes are $50. Calculate NDP at market price.", a: "$900", options: ["$950", "$850", "$900", "$1,150"]},
  {q: "Calculate Real GDP if Nominal GDP is $600B and the GDP Deflator is 120.", a: "$500B", options: ["$720B", "$500B", "$480B", "$600B"]},
  {q: "A Gini Coefficient of 0.65 compared to 0.25 indicates ______.", a: "Higher inequality", options: ["Lower inequality", "Higher growth", "Higher population", "Higher inequality"]},
  {q: "If the Dependency Ratio is 80% with 40 million workers, how many are dependents?", a: "32 million", options: ["32 million", "8 million", "20 million", "50 million"]},
  {q: "The Rule of 70: If an economy grows at 7% per year, it will double in ______.", a: "10 years", options: ["7 years", "10 years", "70 years", "14 years"]},
  {q: "Calculate the working population if the total population is 100M and 40% are children/elderly.", a: "60M", options: ["40M", "60M", "100M", "20M"]},
  {q: "Investment is $200M and Capital-Output Ratio is 4. Calculate the increase in GDP.", a: "$50M", options: ["$800M", "$50M", "$200M", "$400M"]},

  // --- Economic Systems ---
  {q: "In a Market Economy, if Qd = 50 - 2P and Qs = 10 + 2P, find equilibrium price.", a: "10", options: ["5", "10", "15", "20"]},
  {q: "Using Q21, if the government sets a price ceiling of P = 5, find the shortage.", a: "20", options: ["10", "20", "40", "5"]},
  {q: "In a Mixed Economy, if the Private Sector is 60% of a $500B GDP, the Public Sector is:", a: "$200B", options: ["$300B", "$200B", "$100B", "$500B"]},
  {q: "A state produces 100 Guns instead of 150 Butter. The Opportunity Cost of 100 Guns is:", a: "150 Butter", options: ["50 Butter", "150 Butter", "100 Butter", "0"]},
  {q: "Bread production rises from 1,000 to 1,500 units; cost rises from $2 to $3. Total cost % increase?", a: "125%", options: ["50%", "100%", "125%", "225%"]},
  {q: "Consumer willing to pay $20 pays $15 instead. Calculate the Consumer Surplus.", a: "$5", options: ["$35", "$5", "$15", "$20"]},
  {q: "Which system typically has the lowest Gini Coefficient (most equal distribution)?", a: "Socialist", options: ["Capitalist", "Socialist", "Mixed", "Traditional"]},
  {q: "A 5% VAT is added to a $200 item. What is the final price?", a: "$210", options: ["$205", "$210", "$195", "$220"]},
  {q: "A planned economy spends 40% of its $2T budget on schools. Amount left for others?", a: "$1.2T", options: ["$0.8T", "$1.2T", "$1.6T", "$0.4T"]},
  {q: "The movement along a PPF curve from one point to another measures ______.", a: "Opportunity cost", options: ["Inflation", "Opportunity cost", "Economic growth", "Total utility"]},

  // --- Development Goals (SDGs) ---
  {q: "Poverty line is $2.15/day. Minimum annual income needed to stay above it (365 days)?", a: "$784.75", options: ["$784.75", "$365.00", "$215.00", "$1,000"]},
  {q: "To move solar usage from 10% to 50% in 5 years, annual percentage point increase needed?", a: "8%", options: ["10%", "5%", "8%", "40%"]},
  {q: "1,200 students with a 1:40 teacher ratio. How many more teachers needed to reach 1:30?", a: "10", options: ["40", "30", "10", "5"]},
  {q: "If emissions must drop by 40% from 500 million tons, what is the new target?", a: "300M", options: ["200M", "300M", "460M", "100M"]},
  {q: "Calculate Literacy Rate: 15 million adults, 9 million can read/write.", a: "60%", options: ["90%", "60%", "15%", "40%"]},
  {q: "Gender Pay Gap is 15%. If men earn $3,000, how much do women earn?", a: "$2,550", options: ["$2,850", "$2,550", "$3,450", "$2,700"]},
  {q: "A village of 5,000 people. One well serves 200/day. Days for everyone to get water once?", a: "25", options: ["10", "20", "25", "50"]},
  {q: "Calculate Under-5 Mortality Rate: 50 deaths per 1,000 live births.", a: "5%", options: ["50%", "5%", "0.5%", "0.05%"]},
  {q: "An economy grows by 7% annually. To quadruple (4x), it takes roughly ______ years.", a: "20 years", options: ["10 years", "7 years", "20 years", "14 years"]},
  {q: "Calculate Food Waste Index: 50kg bought, 8kg thrown away.", a: "16%", options: ["8%", "16%", "25%", "10%"]},

  // --- International Organisations ---
  {q: "IMF loan of $1B at 2% annual simple interest. Total interest after 3 years?", a: "$60M", options: ["$20M", "$60M", "$1.06B", "$6M"]},
  {q: "World Bank project costs $500M (60% grant, 40% loan). What is the loan amount?", a: "$200M", options: ["$300M", "$200M", "$100M", "$50M"]},
  {q: "ECOWAS removes a 15% tariff on a $1,000 item. How much is saved?", a: "$150", options: ["$15", "$150", "$850", "$115"]},
  {q: "AfDB invests $200M with a 5% Social Return (SROI). Value of return?", a: "$10M", options: ["$1M", "$10M", "$5M", "$50M"]},
  {q: "A 100% retaliatory tariff is placed on a $20M good. New cost?", a: "$40M", options: ["$20M", "$40M", "$100M", "$0"]},
  {q: "Average GDP of bloc: $10B, $15B, $20B, $5B, $50B.", a: "$20B", options: ["$100B", "$25B", "$20B", "$15B"]},
  {q: "OPEC cuts supply by 2M barrels from 30M barrels. Percentage decrease?", a: "6.67%", options: ["15%", "6.67%", "2%", "10%"]},
  {q: "IMF quota is 0.5%. Total SDR pool is $640B. Country's share?", a: "$3.2B", options: ["$32B", "$3.2B", "$0.5B", "$6.4B"]},
  {q: "UN funding is 0.01% of GDP. If GDP is $400B, the contribution is ______.", a: "$40M", options: ["$4M", "$40M", "$400k", "$400M"]},
  {q: "A country's total trade is $100B; its trade with Country B is $20B. Country B's share is:", a: "20%", options: ["10%", "20%", "5%", "80%"]} 
 ]
};